# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: my-ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - run: npm i
    - run: npx nx build ng-playground
    
    - name: Deploy to akita.surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'simple-akita.surge.sh'
        project: 'dist/packages/ng-playground'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}
